### ISSUE TITLE
Update for NB8.1?

### ISSUE THREAD

**Issue by Git-GT** [giancosta86/EasyPmd#10]
Hi Gianluca,
I just switched to Netbeans 8.1 and noticed that there is not a compatible version of your plugin. 
Do you have any approximate idea about when you will release a compatible version?
Thanks and best regards,

**Comment by giancosta86** [comment]
Hi! ^__^ 

EasyPmd 9.3 for NetBeans 8.0 seems to run fine in NetBeans 8.1, so I have requested its verification for NetBeans 8.1: it should appear in the _Plugins_ list in a few days; meanwhile, you might want to [download it from GitHub](https://github.com/giancosta86/EasyPmd/releases/latest/) or from the [NetBeans Plugin Portal](http://plugins.netbeans.org/plugin/57270/easypmd)! ^__^

Best regards

**Comment by Git-GT** [comment]
Thank you very very much,
have a nice day!

Best regards,

**Comment by giancosta86** [comment]
Have a nice day, you too! ^__^

Best regards
