### ISSUE TITLE
EasyPmd fails silently on ruleset problems

### ISSUE THREAD

**Issue by Zero3** [giancosta86/EasyPmd#11]
EasyPmd silently stopped working for me because an update removed the `BooleanInversion` rule which I had excluded in my ruleset file as follows. Once I realized EasyPmd had stopped warning me about things, I went to the settings dialog and pressed "Verify options" which revealed the underlying problem.

I suggest that EasyPmd displays some kind of warning when it fails to run because of an ruleset issue like this one.

**Comment by giancosta86** [comment]
I'm afraid I'd need further information about such issue... It seems that EasyPmd actually _shows_ warnings in case of errors in rulesets... what was, exactly, the update which you mentioned? What was your ruleset?

**Comment by Zero3** [comment]
You are absolutely correct. I think I messed something up while debugging #1. An error is correctly displayed when I try to reproduce now. My bad!
