### ISSUE TITLE
exclude-pattern not supported

### ISSUE THREAD

**Issue by Zero3** [giancosta86/EasyPmd#12]
It appears like the `<exclude-pattern>` tag in rulesets is silently ignored by EasyPmd. A warning about this could be nice. Support for it could be awesome :).

**Comment by giancosta86** [comment]
That was a great suggestion, thanks! :) I have implemented it - both **exclude-pattern** and **include-pattern**. Stay tuned for the coming release! ^__^

**Comment by Zero3** [comment]
Great! I'll give it a shot! Thanks.
