### ISSUE TITLE
Netbeans 8.2 Support

### ISSUE THREAD

**Issue by Adam97234** [giancosta86/EasyPmd#13]
Any chance you could add EasyPmd to be usable in Netbeans 8.2?  Also, thanks for the plugin, I use it every day.

**Comment by giancosta86** [comment]
I couldn't release it earlier as it's a very busy period - but voilà! ^__^!
https://www.facebook.com/easypmd/posts/558490887681395

Thanks for using EasyPmd! ^__^

**Comment by Adam97234** [comment]
Really appreciate the quick turnaround.  I do code reviews for> 20 developers and I require that their code passes PMD before they can mark everything complete.  Your work helps us write better code.  Molte grazie!

**Comment by giancosta86** [comment]
Di nulla! You're welcome! ^___^!
